// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zcyeptollkxrnfteyswe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpjeWVwdG9sbGt4cm5mdGV5c3dlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkzNTA5NjEsImV4cCI6MjA1NDkyNjk2MX0.HdH-yP5WnUfyESQu7Jpw2Cuzjr0WaoabEhqJweprhzY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);